export interface JobProfileConfig {
  name: string;
  targetTitles: string[];
  persianTitles: string[];
  coreSkills: string[];
  bonusSkills: string[];
  negativeKeywords: string[];
  targetExperienceYears: { min: number; max: number };
  targetLocations: string[];
  disallowedLocations: string[];
}

export const DESIGN_PROFILE: JobProfileConfig = {
  name: 'UI/UX & Product Design',
  targetLocations: ['تهران', 'tehran'],
  disallowedLocations: [
    'اصفهان',
    'isfahan',
    'esfahan',
    'مشهد',
    'mashhad',
    'شیراز',
    'shiraz',
    'تبریز',
    'tabriz',
    'کرج',
    'karaj',
    'یزد',
    'yazd',
    'قم',
    'qom',
    'رشت',
    'rasht',
    'اهواز',
    'ahvaz',
    'کرمان',
    'kerman',
    'ارومیه',
    'urmia',
    'ساری',
    'sari',
    'همدان',
    'hamedan',
    'کرمانشاه',
    'kermanshah',
    'قزوین',
    'qazvin',
    'زاهدان',
    'zahedan',
    'بوشهر',
    'bushehr',
    'بندرعباس',
    'bandar abbas',
    'اراک',
    'arak',
    'زنجان',
    'zanjan',
    'سنندج',
    'sanandaj',
    'خرم آباد',
    'khorramabad',
    'گرگان',
    'gorgan',
    'بابل',
    'babol',
    'کاشان',
    'kashan',
    'کیش',
    'kish',
  ],
  targetTitles: [
    'product designer',
    'ui/ux designer',
    'ui designer',
    'ux designer',
    'ui ux designer',
    'interaction designer',
    'visual designer',
    'ux researcher',
    'user experience designer',
    'user interface designer',
    'lead product designer',
    'senior product designer',
    'senior ui/ux designer',
  ],
  persianTitles: [
    'طراح محصول',
    'طراح رابط کاربری',
    'طراح تجربه کاربری',
    'طراح محصول و تجربه کاربری',
    'طراح ui/ux',
    'طراح ui ux',
    'طراح ui',
    'طراح ux',
    'پژوهشگر تجربه کاربری',
    'محقق ux',
    'طراح دیزاین سیستم',
    'طراح بصری',
  ],
  coreSkills: [
    'figma',
    'design system',
    'design systems',
    'ui/ux',
    'ui ux',
    'wireframing',
    'prototyping',
    'user research',
    'user testing',
    'information architecture',
    'usability testing',
    'user flow',
    'journey mapping',
    'sketch',
    'adobe xd',
  ],
  bonusSkills: [
    'micro-interactions',
    'framer',
    'principle',
    'lottie',
    'heuristic evaluation',
    'design sprint',
    'agile',
    'scrum',
    'a/b testing',
    'analytics',
  ],
  negativeKeywords: [
    'frontend developer',
    'front-end developer',
    'react developer',
    'vue developer',
    'angular developer',
    'full stack',
    'backend developer',
    'چاپ و بسته بندی',
    'طراح چاپ',
    'کانون تبلیغاتی',
    'بنر تبلیغاتی',
    '3d max',
    'maya',
    'blender',
    'طراح دکوراسیون',
    'طراح صنعتی',
    'معماری داخلی',
    'کارشناس فروش',
    'پشتیبان سایت',
    'ادمین اینستاگرام',
    'تولید محتوا متنی',
  ],
  targetExperienceYears: {
    min: 1,
    max: 4,
  },
};
